# Generated by Django 4.1 on 2022-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omok',
            name='chat',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='omok',
            name='moves',
            field=models.JSONField(null=True),
        ),
    ]
