# Generated by Django 4.1 on 2022-08-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omok', '0002_alter_omok_chat_alter_omok_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omok',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='omok',
            name='opponent',
        ),
        migrations.AddField(
            model_name='omok',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='omok_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='omok',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='omok_white', to=settings.AUTH_USER_MODEL),
        ),
    ]
