# Generated by Django 4.1 on 2022-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_minesweeper_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeper',
            name='board',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='minesweeper',
            name='moves',
            field=models.JSONField(null=True),
        ),
    ]
